services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /app/tmp
    working_dir: /app
    command: air -c .air.toml
