services:
  rh-pos-be:
    image: ghcr.io/usernamesalah/rh-pos:latest
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${SERVER_PORT:-8080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - usernamesalah

networks:
  usernamesalah:
    external: true
